# Generated by Django 5.1.1 on 2024-10-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="dt_created_at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, db_column="dt_modified_at"),
                ),
                ("active", models.BooleanField(db_column="cs_active", default=True)),
                ("name", models.CharField(db_column="tx_name", max_length=70)),
                ("age", models.IntegerField(db_column="nb_age")),
                ("rg", models.CharField(db_column="tx_rg", max_length=12)),
                (
                    "cpf",
                    models.CharField(db_column="tx_cpf", max_length=12, unique=True),
                ),
            ],
            options={"db_table": "client", "managed": True,},
        ),
    ]
