# Generated by Django 5.1.1 on 2024-10-24 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="dt_created_at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, db_column="dt_modified_at"),
                ),
                ("active", models.BooleanField(db_column="cs_active", default=True)),
                ("name", models.CharField(db_column="tx_name", max_length=70)),
                (
                    "registration",
                    models.CharField(
                        db_column="tx_registration", max_length=15, unique=True
                    ),
                ),
            ],
            options={"db_table": "employee", "managed": True,},
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="dt_created_at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, db_column="dt_modified_at"),
                ),
                ("active", models.BooleanField(db_column="cs_active", default=True)),
                ("description", models.TextField(db_column="tx_description")),
                ("quantity", models.IntegerField(db_column="nb_quantity", default=0)),
            ],
            options={"db_table": "product", "managed": True,},
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="dt_created_at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, db_column="dt_modified_at"),
                ),
                ("active", models.BooleanField(db_column="cs_active", default=True)),
                ("nrf", models.CharField(db_column="tx_nrf", max_length=255)),
                (
                    "client",
                    models.ForeignKey(
                        db_column="client_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.client",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        db_column="employee_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.employee",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.product",
                    ),
                ),
            ],
            options={"db_table": "sale", "managed": True,},
        ),
    ]
