# Generated by Django 5.1.1 on 2024-10-10 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('core', '0002_employee_product_sale')]

    operations = [
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS unaccent;'),
    ]
