# Generated by Django 5.1.1 on 2024-10-07 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='emplyee',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='sale',
            table='sale',
        ),
    ]
